FROM owasp/modsecurity-crs:nginx-alpine

ADD https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/install-ngxblocker /usr/local/sbin/install-ngxblocker

USER root

RUN apk update && \
    apk upgrade && \
    apk add bind-tools wget

RUN cd /usr/local/sbin/ && \
    chmod 777 install-ngxblocker && \
    env -u SSL_CERT_FILE -u SSL_CERT_KEY_FILE ./install-ngxblocker -x && \
    chmod 777 *-ngxblocker

RUN env -u SSL_CERT_FILE -u SSL_CERT_KEY_FILE setup-ngxblocker -x -e template -v /etc/nginx/templates/conf.d/ -c /etc/nginx/templates/conf.d -m /etc/nginx/templates/nginx.conf.template && \
    chown nginx:nginx /etc/nginx/conf.d/* && \
    chown nginx:nginx /etc/nginx/bots.d/* && \
    chmod 664 /etc/nginx/bots.d/* && \
    chmod 664 /etc/nginx/conf.d/*

USER nginx